In [1]:
import pandas as pd
import numpy as np 
import warnings
warnings.filterwarnings("ignore")

In [2]:
df = pd.read_csv(r"C:\Users\ASUS\Downloads\archive (4)\Zomato Dataset.csv", index_col = 0)
df

,Delivery_person_ID,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Order_Date,Time_Orderd,Time_Order_picked,Weather_conditions,Road_traffic_density,Vehicle_condition,Type_of_order,Type_of_vehicle,multiple_deliveries,Festival,City,Time_taken (min)
ID,,,,,,,,,,,,,,,,,,,
0xcdcd,DEHRES17DEL01,36.0,4.2,30.327968,78.046106,30.397968,78.116106,12-02-2022,21:55,22:10,Fog,Jam,2,Snack,motorcycle,3.0,No,Metropolitian,46
0xd987,KOCRES16DEL01,21.0,4.7,10.003064,76.307589,10.043064,76.347589,13-02-2022,14:55,15:05,Stormy,High,1,Meal,motorcycle,1.0,No,Metropolitian,23
0x2784,PUNERES13DEL03,23.0,4.7,18.562450,73.916619,18.652450,74.006619,04-03-2022,17:30,17:40,Sandstorms,Medium,1,Drinks,scooter,1.0,No,Metropolitian,21
0xc8b6,LUDHRES15DEL02,34.0,4.3,30.899584,75.809346,30.919584,75.829346,13-02-2022,09:20,09:30,Sandstorms,Low,0,Buffet,motorcycle,0.0,No,Metropolitian,20
0xdb64,KNPRES14DEL02,24.0,4.7,26.463504,80.372929,26.593504,80.502929,14-02-2022,19:50,20:05,Fog,Jam,1,Snack,scooter,1.0,No,Metropolitian,41
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0x7c09,JAPRES04DEL01,30.0,4.8,26.902328,75.794257,26.912328,75.804257,24-03-2022,11:35,11:45,Windy,High,1,Meal,motorcycle,0.0,No,Metropolitian,32
0xd641,AGRRES16DEL01,21.0,4.6,0.000000,0.000000,0.070000,0.070000,16-02-2022,19:55,20:10,Windy,Jam,0,Buffet,motorcycle,1.0,No,Metropolitian,36
0x4f8d,CHENRES08DEL03,30.0,4.9,13.022394,80.242439,13.052394,80.272439,11-03-2022,23:50,24:05:00,Cloudy,Low,1,Drinks,scooter,0.0,No,Metropolitian,16
0x5eee,COIMBRES11DEL01,20.0,4.7,11.001753,76.986241,11.041753,77.026241,07-03-2022,13:35,13:40,Cloudy,High,0,Snack,motorcycle,1.0,No,Metropolitian,26
0x5fb2,RANCHIRES09DEL02,23.0,4.9,23.351058,85.325731,23.431058,85.405731,02-03-2022,17:10,17:15,Fog,Medium,2,Snack,scooter,1.0,No,Metropolitian,36

In [3]:
df.head()

,Delivery_person_ID,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Order_Date,Time_Orderd,Time_Order_picked,Weather_conditions,Road_traffic_density,Vehicle_condition,Type_of_order,Type_of_vehicle,multiple_deliveries,Festival,City,Time_taken (min)
ID,,,,,,,,,,,,,,,,,,,
0xcdcd,DEHRES17DEL01,36.0,4.2,30.327968,78.046106,30.397968,78.116106,12-02-2022,21:55,22:10,Fog,Jam,2,Snack,motorcycle,3.0,No,Metropolitian,46
0xd987,KOCRES16DEL01,21.0,4.7,10.003064,76.307589,10.043064,76.347589,13-02-2022,14:55,15:05,Stormy,High,1,Meal,motorcycle,1.0,No,Metropolitian,23
0x2784,PUNERES13DEL03,23.0,4.7,18.562450,73.916619,18.652450,74.006619,04-03-2022,17:30,17:40,Sandstorms,Medium,1,Drinks,scooter,1.0,No,Metropolitian,21
0xc8b6,LUDHRES15DEL02,34.0,4.3,30.899584,75.809346,30.919584,75.829346,13-02-2022,09:20,09:30,Sandstorms,Low,0,Buffet,motorcycle,0.0,No,Metropolitian,20
0xdb64,KNPRES14DEL02,24.0,4.7,26.463504,80.372929,26.593504,80.502929,14-02-2022,19:50,20:05,Fog,Jam,1,Snack,scooter,1.0,No,Metropolitian,41

In [6]:
df.tail()

,Delivery_person_ID,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Order_Date,Time_Orderd,Time_Order_picked,Weather_conditions,Road_traffic_density,Vehicle_condition,Type_of_order,Type_of_vehicle,multiple_deliveries,Festival,City,Time_taken (min)
ID,,,,,,,,,,,,,,,,,,,
0x7c09,JAPRES04DEL01,30.0,4.8,26.902328,75.794257,26.912328,75.804257,24-03-2022,11:35,11:45,Windy,High,1,Meal,motorcycle,0.0,No,Metropolitian,32
0xd641,AGRRES16DEL01,21.0,4.6,0.000000,0.000000,0.070000,0.070000,16-02-2022,19:55,20:10,Windy,Jam,0,Buffet,motorcycle,1.0,No,Metropolitian,36
0x4f8d,CHENRES08DEL03,30.0,4.9,13.022394,80.242439,13.052394,80.272439,11-03-2022,23:50,24:05:00,Cloudy,Low,1,Drinks,scooter,0.0,No,Metropolitian,16
0x5eee,COIMBRES11DEL01,20.0,4.7,11.001753,76.986241,11.041753,77.026241,07-03-2022,13:35,13:40,Cloudy,High,0,Snack,motorcycle,1.0,No,Metropolitian,26
0x5fb2,RANCHIRES09DEL02,23.0,4.9,23.351058,85.325731,23.431058,85.405731,02-03-2022,17:10,17:15,Fog,Medium,2,Snack,scooter,1.0,No,Metropolitian,36

In [9]:
df.describe()

,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Vehicle_condition,multiple_deliveries,Time_taken (min)
count,43730.000000,43676.000000,45584.000000,45584.000000,45584.000000,45584.000000,45584.000000,44591.000000,45584.000000
mean,29.566911,4.633774,17.017948,70.229684,17.465480,70.844161,1.023385,0.744635,26.293963
std,5.815064,0.334744,8.185674,22.885575,7.335562,21.120578,0.839055,0.572510,9.384298
min,15.000000,1.000000,-30.905562,-88.366217,0.010000,0.010000,0.000000,0.000000,10.000000
25%,25.000000,4.500000,12.933284,73.170000,12.988453,73.280000,0.000000,0.000000,19.000000
50%,30.000000,4.700000,18.551440,75.897963,18.633934,76.002574,1.000000,1.000000,26.000000
75%,35.000000,4.900000,22.728163,78.044095,22.785049,78.107044,2.000000,1.000000,32.000000
max,50.000000,6.000000,30.914057,88.433452,31.054057,88.563452,3.000000,3.000000,54.000000

In [11]:
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Rows: 45584
Columns: 19

In [13]:
df.columns

Index(['Delivery_person_ID', 'Delivery_person_Age', 'Delivery_person_Ratings',
       'Restaurant_latitude', 'Restaurant_longitude',
       'Delivery_location_latitude', 'Delivery_location_longitude',
       'Order_Date', 'Time_Orderd', 'Time_Order_picked', 'Weather_conditions',
       'Road_traffic_density', 'Vehicle_condition', 'Type_of_order',
       'Type_of_vehicle', 'multiple_deliveries', 'Festival', 'City',
       'Time_taken (min)'],
      dtype='object')

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 45584 entries, 0xcdcd to 0x5fb2
Data columns (total 19 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Delivery_person_ID           45584 non-null  object
 1   Delivery_person_Age          43730 non-null  float64
 2   Delivery_person_Ratings      43676 non-null  float64
 3   Restaurant_latitude          45584 non-null  float64
 4   Restaurant_longitude         45584 non-null  float64
 5   Delivery_location_latitude   45584 non-null  float64
 6   Delivery_location_longitude  45584 non-null  float64
 7   Order_Date                   45584 non-null  object
 8   Time_Orderd                  43853 non-null  object
 9   Time_Order_picked            45584 non-null  object
 10  Weather_conditions           44968 non-null  object
 11  Road_traffic_density         44983 non-null  object
 12  Vehicle_condition            45584 non-null  int64
 13  Type_of_order                45584 non-null  object
 14  Type_of_vehicle              45584 non-null  object
 15  multiple_deliveries          44591 non-null  float64
 16  Festival                     45356 non-null  object
 17  City                         44384 non-null  object
 18  Time_taken (min)             45584 non-null  int64
dtypes: float64(7), int64(2), object(10)
memory usage: 7.0+ MB

In [17]:
print(len(df.columns))
df.columns

19

Index(['Delivery_person_ID', 'Delivery_person_Age', 'Delivery_person_Ratings',
       'Restaurant_latitude', 'Restaurant_longitude',
       'Delivery_location_latitude', 'Delivery_location_longitude',
       'Order_Date', 'Time_Orderd', 'Time_Order_picked', 'Weather_conditions',
       'Road_traffic_density', 'Vehicle_condition', 'Type_of_order',
       'Type_of_vehicle', 'multiple_deliveries', 'Festival', 'City',
       'Time_taken (min)'],
      dtype='object')

In [19]:
# Lowering all the columns so there is no typo while mentioning column names
df.columns = [col.lower() for col in df.columns]

In [21]:
df.head()
df.columns

Index(['delivery_person_id', 'delivery_person_age', 'delivery_person_ratings',
       'restaurant_latitude', 'restaurant_longitude',
       'delivery_location_latitude', 'delivery_location_longitude',
       'order_date', 'time_orderd', 'time_order_picked', 'weather_conditions',
       'road_traffic_density', 'vehicle_condition', 'type_of_order',
       'type_of_vehicle', 'multiple_deliveries', 'festival', 'city',
       'time_taken (min)'],
      dtype='object')

In [23]:
# Check missing Value

In [25]:
df.isnull().sum().sort_values(ascending=False)

delivery_person_ratings        1908
delivery_person_age            1854
time_orderd                    1731
city                           1200
multiple_deliveries             993
weather_conditions              616
road_traffic_density            601
festival                        228
delivery_person_id                0
vehicle_condition                 0
type_of_vehicle                   0
type_of_order                     0
time_order_picked                 0
order_date                        0
delivery_location_longitude       0
delivery_location_latitude        0
restaurant_longitude              0
restaurant_latitude               0
time_taken (min)                  0
dtype: int64

In [27]:
df = df.dropna(subset=["time_orderd"])
df.isnull().sum()

delivery_person_id                0
delivery_person_age             214
delivery_person_ratings         268
restaurant_latitude               0
restaurant_longitude              0
delivery_location_latitude        0
delivery_location_longitude       0
order_date                        0
time_orderd                       0
time_order_picked                 0
weather_conditions                0
road_traffic_density              0
vehicle_condition                 0
type_of_order                     0
type_of_vehicle                   0
multiple_deliveries             943
festival                        219
city                           1144
time_taken (min)                  0
dtype: int64

In [29]:
df["delivery_person_age"] = df["delivery_person_age"].fillna(
    df["delivery_person_age"].median()
)

df["delivery_person_ratings"] = df["delivery_person_ratings"].fillna(
    df["delivery_person_ratings"].median()
)

In [31]:
df.isnull().sum()

delivery_person_id                0
delivery_person_age               0
delivery_person_ratings           0
restaurant_latitude               0
restaurant_longitude              0
delivery_location_latitude        0
delivery_location_longitude       0
order_date                        0
time_orderd                       0
time_order_picked                 0
weather_conditions                0
road_traffic_density              0
vehicle_condition                 0
type_of_order                     0
type_of_vehicle                   0
multiple_deliveries             943
festival                        219
city                           1144
time_taken (min)                  0
dtype: int64

In [33]:
df["multiple_deliveries"] = df["multiple_deliveries"].fillna(0)

In [35]:
df["festival"] = df["festival"].fillna("No")

In [37]:
df["city"] = df["city"].fillna("Unknown")

In [39]:
df.isnull().sum()

delivery_person_id             0
delivery_person_age            0
delivery_person_ratings        0
restaurant_latitude            0
restaurant_longitude           0
delivery_location_latitude     0
delivery_location_longitude    0
order_date                     0
time_orderd                    0
time_order_picked              0
weather_conditions             0
road_traffic_density           0
vehicle_condition              0
type_of_order                  0
type_of_vehicle                0
multiple_deliveries            0
festival                       0
city                           0
time_taken (min)               0
dtype: int64

In [41]:
df["order_date"] = pd.to_datetime(df["order_date"], dayfirst=True)

In [43]:
df["time_orderd"] = pd.to_datetime(df["time_orderd"], format="%H:%M:%S", errors="coerce").dt.time
df["time_order_picked"] = pd.to_datetime(df["time_order_picked"], format="%H:%M:%S", errors="coerce").dt.time

In [45]:
df["order_hour"] = pd.to_datetime(df["time_orderd"].astype(str)).dt.hour

In [47]:
df[["time_orderd", "order_hour"]].head()

       time_orderd  order_hour
ID
0xcdcd         NaT         NaN
0xd987         NaT         NaN
0x2784         NaT         NaN
0xc8b6         NaT         NaN
0xdb64         NaT         NaN

In [49]:
df["time_slot"] = np.where(
    ((df["order_hour"] >= 11) & (df["order_hour"] <= 14)) |             ####Create Peak / Off-Peak Flag
    ((df["order_hour"] >= 18) & (df["order_hour"] <= 22)),
    "Peak",
    "Off-Peak"
)

In [51]:
df[["order_hour", "time_slot"]].head(10)

        order_hour time_slot
ID
0xcdcd         NaN  Off-Peak
0xd987         NaN  Off-Peak
0x2784         NaN  Off-Peak
0xc8b6         NaN  Off-Peak
0xdb64         NaN  Off-Peak
0x3af3         NaN  Off-Peak
0x3aab         NaN  Off-Peak
0x689b         NaN  Off-Peak
0x6f67         NaN  Off-Peak
0xc9cf         NaN  Off-Peak

In [53]:
df = df.rename(columns={
    "weather_conditions": "weather",
    "road_traffic_density": "traffic_density",
    "type_of_vehicle": "vehicle_type",
    "type_of_order": "order_type",
    "time_orderd": "order_time",
    "time_order_picked": "order_picked_time",
    "time_taken (min)": "delivery_time_min"
})

In [55]:
text_cols = [
    "weather",
    "traffic_density",
    "order_type",
    "vehicle_type",
    "festival",
    "city"
]

for col in text_cols:
    df[col] = df[col].astype(str).str.strip().str.title()

In [57]:
df[text_cols].head()

,weather,traffic_density,order_type,vehicle_type,festival,city
ID,,,,,,
0xcdcd,Fog,Jam,Snack,Motorcycle,No,Metropolitian
0xd987,Stormy,High,Meal,Motorcycle,No,Metropolitian
0x2784,Sandstorms,Medium,Drinks,Scooter,No,Metropolitian
0xc8b6,Sandstorms,Low,Buffet,Motorcycle,No,Metropolitian
0xdb64,Fog,Jam,Snack,Scooter,No,Metropolitian

In [59]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 43853 entries, 0xcdcd to 0x5fb2
Data columns (total 21 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   delivery_person_id           43853 non-null  object
 1   delivery_person_age          43853 non-null  float64
 2   delivery_person_ratings      43853 non-null  float64
 3   restaurant_latitude          43853 non-null  float64
 4   restaurant_longitude         43853 non-null  float64
 5   delivery_location_latitude   43853 non-null  float64
 6   delivery_location_longitude  43853 non-null  float64
 7   order_date                   43853 non-null  datetime64[ns]
 8   order_time                   0 non-null      datetime64[ns]
 9   order_picked_time            0 non-null      datetime64[ns]
 10  weather                      43853 non-null  object
 11  traffic_density              43853 non-null  object
 12  vehicle_condition            43853 non-null  int64
 13  order_type                   43853 non-null  object
 14  vehicle_type                 43853 non-null  object
 15  multiple_deliveries          43853 non-null  float64
 16  festival                     43853 non-null  object
 17  city                         43853 non-null  object
 18  delivery_time_min            43853 non-null  int64
 19  order_hour                   0 non-null      float64
 20  time_slot                    43853 non-null  object
dtypes: datetime64[ns](3), float64(8), int64(2), object(8)
memory usage: 8.4+ MB

In [61]:
df = df.dropna(subset=["order_time", "order_picked_time", "order_hour"])

In [63]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 21 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   delivery_person_id           0 non-null      object
 1   delivery_person_age          0 non-null      float64
 2   delivery_person_ratings      0 non-null      float64
 3   restaurant_latitude          0 non-null      float64
 4   restaurant_longitude         0 non-null      float64
 5   delivery_location_latitude   0 non-null      float64
 6   delivery_location_longitude  0 non-null      float64
 7   order_date                   0 non-null      datetime64[ns]
 8   order_time                   0 non-null      datetime64[ns]
 9   order_picked_time            0 non-null      datetime64[ns]
 10  weather                      0 non-null      object
 11  traffic_density              0 non-null      object
 12  vehicle_condition            0 non-null      int64
 13  order_type                   0 non-null      object
 14  vehicle_type                 0 non-null      object
 15  multiple_deliveries          0 non-null      float64
 16  festival                     0 non-null      object
 17  city                         0 non-null      object
 18  delivery_time_min            0 non-null      int64
 19  order_hour                   0 non-null      float64
 20  time_slot                    0 non-null      object
dtypes: datetime64[ns](3), float64(8), int64(2), object(8)
memory usage: 0.0+ bytes

In [65]:
df.to_csv(r"C:\Users\ASUS\downloads\zomato_delivery_clean.csv", index=False)

In [67]:
import os
os.getcwd()

'C:\\Users\\ASUS'